# Architecture
model_type: ResNet34_001_p01_imagenet100

# ===== Dataset ===== #
dataset: ImageNet100
num_classes: 100
log_dir: ./runs/imagenet100-resnet34-bnn-biconnect/
normalize: imagenet100
valid_ratio: 0.02

# ===== Learning Rate Policy ======== #
optimizer: adam
lr: 0.0005
lr_policy: cosine_lr
alpha: 0

# ===== Network training config ===== #
epochs: 100
weight_decay: 0.0005
momentum: 0.9
batch_size: 512
trainer: adv_step_fast
attack: {name: FGSM-RS, step_size: 1, threshold: 2, n_class: 100}
eval_attack: {name: PGD, step_size: 0.00196078, threshold: 2, iter_num: 10}

# ===== Sparsity =========== #
conv_type: BinConv
bn_type: LearnedBatchNorm
nonlinearity: relu
prune_rate: 1.0

# ===== Hardware setup ===== #
workers: 20
seed: 1234
