# Architecture
model_type: ResNet34_imagenet100

# ===== Dataset ===== #
dataset: Imagenet100
num_classes: 100
log_dir: ./runs/imagenet100-resnet34/aa
normalize: imagenet100

# ===== Network training config ===== #
batch_size: 256
attack: {norm: Linf, threshold: 2}
subset: test

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
freeze_weights: True
mode: fan_in
nonlinearity: relu
scale_fan: True

# ===== Hardware setup ===== #
workers: 20
seed: 1234
