# ===== Dataset ===== #
dataset: CIFAR100
num_classes: 100
log_dir: ./runs/cifar100-smallnet/aa
normalize: cifar100

# ===== Network training config ===== #
batch_size: 512
attack: {norm: Linf, threshold: 4}
subset: test

# ===== Sparsity =========== #
conv_type: BinConv
bn_type: LearnedBatchNorm
nonlinearity: relu

# ===== Hardware setup ===== #
workers: 20
seed: 1234
