# Architecture
model_type: ResNet18_001_p1_cifar100

# ===== Dataset ===== #
dataset: CIFAR100
num_classes: 100
log_dir: ./runs/cifar100-resnet18-001/
normalize: cifar100
valid_ratio: 0.02

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.01
lr_policy: multistep_lr
lr_gamma: 0.1
lr_adjust: 100

# ===== Network training config ===== #
epochs: 400
weight_decay: 0.0005
momentum: 0.9
batch_size: 512
trainer: adv_step
attack: {name: PGD, step_size: 1, threshold: 4, iter_num: 10}

# ===== Sparsity =========== #
conv_type: DenseConv
bn_type: LearnedBatchNorm
nonlinearity: relu
prune_rate: 1.0

# ===== Hardware setup ===== #
workers: 20
seed: 1234
