# Architecture
model_type: cResNet50

# ===== Dataset ===== #
dataset: CIFAR10
num_classes: 10
log_dir: ./runs/cifar10-resnet50/aa
normalize: cifar10

# ===== Network training config ===== #
batch_size: 512
attack: {norm: Linf, threshold: 8}
subset: test

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
freeze_weights: True
mode: fan_in
nonlinearity: relu
scale_fan: True

# ===== Hardware setup ===== #
workers: 20
seed: 1234
