# Architecture
model_type: cResNet50

# ===== Dataset ===== #
dataset: CIFAR10
num_classes: 10
log_dir: ./runs/cifar10-resnet50-binary-weights/
normalize: cifar10
valid_ratio: 0.02

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_policy: cosine_lr
alpha: 0

# ===== Network training config ===== #
epochs: 400
weight_decay: 0.0005
momentum: 0.9
batch_size: 256
trainer: adv_step
attack: {name: PGD, step_size: 2, threshold: 8, iter_num: 10}

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
freeze_weights: True
init: binary
mode: fan_in
nonlinearity: relu
# prune_rate: 0.01
scale_fan: True

# ===== Hardware setup ===== #
workers: 20
seed: 1234
