# Architecture
model_type: cResNet34_cifar100

# ===== Dataset ===== #
dataset: CIFAR100
num_classes: 100
log_dir: ./runs/cifar100-resnet34-fp-at-aa/
normalize: cifar100
valid_ratio: 0.02

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_policy: manual_multistep_lr
lr_gamma: 0.1
lr_epochs: [200,300,400]

# ===== Network training config ===== #
epochs: 40
weight_decay: 0.0005
momentum: 0.9
batch_size: 512
trainer: adv_step
attack: {name: simple-aa, threshold: 4, norm: Linf}

# ===== Sparsity =========== #
conv_type: DenseConv
bn_type: LearnedBatchNorm
nonlinearity: relu
prune_rate: 1.0

# ===== Hardware setup ===== #
workers: 20
seed: 1234
